#!/bin/bash
#!/usr/bin python3

# This daemon manages the starting and stopping of the euler_engine to limit Blender to rendering 359 images per axis
# (XYZ), per class. Remaining images are generated by the augment_engine and finally the VOC dataset is assembled by the
# VOCbuilder
# burnsca@

echo "Blender is rendering images..."

# Use blender to render the image on each degree of X , Y and Z axis then exit
blender -b -noaudio -E CYCLES --python euler_engine.py -- handtools 1

echo "Blender is finished rendering, begin augmentation process..."

python3 augment_engine.py

python3 split.py

python3 util.py