#!/bin/bash

blender-2.82a-linux64/blender --background -b -noaudio -E CYCLES --python euler_engine.py -- $1 $2 $3 $4 $5 $6  

python3 augment_engine.py -- $1 $2 $3 $4 $5 $6

python3 split.py -- $1 $2 $3 $4 $5 $6